### PR TITLE
First version with differential absorption spectra functionality.

### PR DESCRIPTION
**Pull request by LucasGVerga**
Added: (dasgenerator.py; createinternalDAS.py; DASplotter.py)

### CODE REVIEW

**Comment by LucasGVerga** [comment]
HI @kavanase. 

Thanks for the feedback. This still is a work in progress. I think I can refactor the code by the end of the week to remove some redundant code.

**Comment by kavanase** [comment]
Ok cool! Yeah no rush, was just checking!

**Comment by LucasGVerga** [comment]
Hi @kavanase, I  refactor some of the code to merge das/tas and Dasplotter/plotter. 

I think we still have room to improve and remove more redundant code in the future. I also added a small change to the from_dict method of Tas and Das classes. If we decide that this is unnecessary we can change it. 

Thanks!

**Comment by kavanase** [comment]
Looks good @LucasGVerga!
If you get a chance at some point, could you add some tests for the DAS calculation/plotting, and a short example notebook for the docs to showcase this functionality, then can add this for a new release 😃

**Comment by LucasGVerga** [comment]
Sure, no problem. 😄

**Comment by kavanase** [comment]
This is looking very nice @LucasGVerga!
I just added some code formatting there (using the `pre-commit` hooks) and refactored some of the function/class/module names for consistency (e.g. usually variable/function/module names are all lowercase (unless a specific reason otherwise) and class names are capitalised).

Some small last bits I think would be good to do and then ready to merge this PR!
- [ ] Would be good to update the `README.md` and docs `index.rst` (home page) to briefly mention the DAS capability, along with the other functionality in the code.
- [ ] Can we update the `TASPlotter` docstring to refer to the fact it can also plot DAS plots now, and how to set `alpha` for this?
- [ ] Can we add some quick plotting tests for the DAS plots as well? You can see the ones written in `test_plotter`. Should be fairly handy as it's just generating some DAS plots with various options, checking they look ok and then saving them as references, and then `pytest-mpl` can do image comparisons of these for the tests.

**Comment by kavanase** [comment]
Something that I was thinking about looking at the updated code and example:
We were talking about it before, that the (i,f) excitation pairs when doing DAS aren't directly comparable and so were removed from the `Das` object. When looking at your example, I realised that it could actually still be quite useful to be able to plot the bare absorption of the new/reference systems with these excitation pairs shown, in the same way that we can do for the light/dark absorption, to analyze the main band-band contributions to absorption changes etc
image

This isn't necessary so we can merge this PR once the above smaller tasks are done, but if you had some time after this PR (though zero rush), would you be able to look at adding this? Sorry to be adding stuff to the list 😅 But I think this would be quite a useful addition and the code should all be there, just a case of adding to the DAS handling. If/when added, would be ideal if we could show this in the example notebook after the DAS plot (and add one or two plotting tests for it).

**Comment by kavanase** [comment]
I had some edits to add to `index.rst`/`README.md` anyway actually 😅 so have mentioned the DAS functionality there. Would be good to add a short line or two to the `Background` part of `index.rst` about the DAS stuff (just copying from the JOSS draft?), but other than that all good on that front!

**Comment by LucasGVerga** [comment]
Hi @kavanase. Thanks for reviewing the code and for the edits to index.rst and README.md. I'll add some other lines to the Background part and check if there is anything else to add. 


Thanks for seeing the TASPlotter docstring, I forgot to alter it after the code refactoring. I'll also add the test to plotting test for DAS.

**Comment by LucasGVerga** [comment]
About the (i,f) excitation pairs, I'll have to test them a bit with different systems to see if they make sense/ bring any insight for different applications of DAS. Initially, I think it could lead to wrong interpretations because the pair (-2,1) of the reference system might not be related to the (-2,1) of the new system. I'll play with that in the future and we can discuss what else we can add to the code 😃 . 

Don't worry about adding things to list hahaha, any idea to make the code better is welcome.

**Comment by kavanase** [comment]
Yeah I see what you mean about the possible confusion due to different band labelling in the different systems, but I guess at least the (i,f) pairs are labelled (e.g. as light/dark in the current code for TAS), do similarly would be labelled "new"/"ref" or similar in the DAS case -- though still ofc still room for confusion in assuming they're directly comparable. 
Could be ok with that and a warning in the tutorials (and docstring) when plotting this to beware that the same (i,f) in the two systems may not always be directly comparable?

**Comment by LucasGVerga** [comment]
It might be a good idea to have that as an option together with a simple warning. I'll try to finish the plotting tests and the other changes for this PR today (so I don't delay the paper submission). As soon as I return from the conference next week, I can start playing again with that and at least add that as an option with a warning.

**Comment by kavanase** [comment]
Cool! All sounds good 😄

**Review by kavanase — APPROVED** [review]
All looks good to me @LucasGVerga! Thanks for all your work on this! 💪 😄 
Happy to merge?

**Comment by LucasGVerga** [comment]
Hi @kavanase, thanks for the support and ideas. Happy to contribute!

**Pull request merged**
